use biblioteca;
SET @OLD_SQL_SAFE_UPDATES = @@SQL_SAFE_UPDATES;
SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM Devolucion;
DELETE FROM Prestamo;
DELETE FROM Libro;
DELETE FROM Cliente;
DELETE FROM Empleado;
DELETE FROM Autor;
DELETE FROM Categoria;

ALTER TABLE Autor AUTO_INCREMENT = 1;
ALTER TABLE Categoria AUTO_INCREMENT = 1;
ALTER TABLE Empleado AUTO_INCREMENT = 1;
ALTER TABLE Cliente AUTO_INCREMENT = 1;
ALTER TABLE Libro AUTO_INCREMENT = 1;
ALTER TABLE Prestamo AUTO_INCREMENT = 1;
ALTER TABLE Devolucion AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
SET SQL_SAFE_UPDATES = @OLD_SQL_SAFE_UPDATES;
